on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: [lint]
    strategy:
      matrix:
        node-version: [18, 20, 22]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.versions}}
      - name: Install
        run: npm ci
      - name: Test
        env:
          PORT: ${{secrets.PORT}}
        run: npm run test
